### ISSUE TITLE
Selects don't get applied when resource template is chosen

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CustomVocab#1]
Adding a new item and choosing a resource template that has custom vocabs set, the form switches to only allowing a literal value, but doesn't create the select of options for that custom vocab. Entering a literal that is not in the custom vocab saves with no problem. 

Will need to check what happens when switching between different resource templates with different custom vocab settings -- a check I haven't tried yet.

**Comment by patrickmj** [comment]
On edit page it _sorta_ works, but seems to be another underlying bug -- if a select has been applied on a property by one resource template, then you switch to other resource template that doesn't apply the custom vocab, the select is still applied to the property.

For example, RT 1 has custom vocab on dcterms:source, RT 2 does not. Switching between the resource templates leaves the select dropdown on dcterms:source

**Comment by jimsafley** [comment]
https://github.com/omeka-s-modules/CustomVocab/issues/1#issue-168381024 is a bug, as you note. But https://github.com/omeka-s-modules/CustomVocab/issues/1#issuecomment-236256634 is expected behavior, if I understand you correctly. Switching between resource templates does not and should not change the data type of existing values.

**Comment by zerocrates** [comment]
I can only reproduce this on Title and Description, as it's an interaction between the data type logic and the later-added "auto-opening" with a text input of the initial Title and Description text fields.

**Comment by zerocrates** [comment]
Should now all be working "as designed" on latest pulls of module and core
