### ISSUE TITLE
Testing: Custom vocabulary of items

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/CustomVocab#12]
The [items-vocab](https://github.com/omeka-s-modules/CustomVocab/tree/items-vocab) branch introduces the ability to use a set of items as a custom vocabulary.

To test this you'll need to upgrade the module, set an item set to a custom vocabulary, apply the custom vocab to a property for a template, and then apply that template when adding or editing an item. You should see a dropdown menu of all items in the configured item set. After saving the item you should see a link to the item resource, with a thumbnail if one exists. After editing the item you should see the drowdown menu with the item resource selected.

**Comment by mebrett** [comment]
When I try to add a vocab populated by an item set, I get an error message "the item set and terms cannot both be empty" despite the fact that I've selected something in the "items" option. 
![Screen Shot 2019-09-24 at 2 22 22 PM](https://user-images.githubusercontent.com/2314070/65539145-d5a15b00-ded6-11e9-9096-759d8152964f.png)

**Comment by mebrett** [comment]
Works as expected. I appreciate that the dropdown includes a search option for item sets with a lot of items in them.
