### ISSUE TITLE
Hierarchy in CustomVocab?

### ISSUE THREAD

**Issue by xavivalenti** [omeka-s-modules/CustomVocab#13]
Hi
Is there any way to implement a hierarchy vocabulary instead of flat vocabulary?
regards
Xavi

**Comment by jimsafley** [comment]
You could simulate a hierarchy by prepending the ancestor branch to each node, like so:

```
Node1
Node1: Node1.1
Node1: Node1.2
Node1: Node1.2: Node1.2.1
Node2
Node2: Node2.1
Node2: Node2.2
```
It's not very elegant, but it's what others have used to implement a hierarchy.
