### ISSUE TITLE
Testing: URI vocab type

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/CustomVocab#18]
The [experimental-uri-type](https://github.com/omeka-s-modules/CustomVocab/tree/experimental-uri-type) branch introduces URI support for vocabularies. The module already supports terms and items, which reflect text and item resource data types, respectively. This branch reflects the URI data type, rounding off the module's support for Omeka S's default data types.

To test this branch, first make sure you have the _released_ version (v1.3.1) already installed, you have some custom vocabularies already created (using both Items and Terms), and you have some items that are described using those custom vocabs. Then upgrade to the experimental-uri-type branch (v1.4.0). Make sure your existing custom vocabs are unchanged, and your items are unchanged.

Once you've confirmed that an upgrade does not adversely affect your data, try out the new "Custom Vocab" interface. There are now three options: Terms, Items, and URIs. Selecting one will render the corresponding field for you to fill out: select Terms to add literal values as your vocab; select Items to add item resources as your vocab; and select URIs to add URIs (and their labels) as your vocab. Make sure each vocab type works - saving Terms/Items/URIs should saves the data, and returning to the form should display only the relevant field.

Pay close attention to the URIs field, given that this branch introduces that feature. As instructed in the field info, enter one URI per line, and you may follow a URI with a space and a label. Add some URIs and add some URI/label combinations, and save the form. Then, while editing a resource template, assign that custom vocab to a property. Then, when adding/editing an item, select the template, add several URIs to the item, and save. The item should now have linked property values - a link that goes to the URI and labeled as the URI itself (if no label) or the label you've assigned to the URI. Make sure to edit the item several times, changing things around, and seeing if anything unexpected happens.

**Comment by sharonmleon** [comment]
Created a vocab with URIs that were from an external Omeka S installation. Added Custom Vocab URI to resource template and created a new item. When I went to create the item, I got the following error:

Notice: Undefined index: @id in /home/sharonml/public_html/6floors.org/workspace/omeka-s/modules/CustomVocab/src/DataType/CustomVocab.php on line 146

Notice: Undefined index: @id in /home/sharonml/public_html/6floors.org/workspace/omeka-s/modules/CustomVocab/src/DataType/CustomVocab.php on line 166

Notice: Undefined index: @id in /home/sharonml/public_html/6floors.org/workspace/omeka-s/modules/CustomVocab/src/DataType/CustomVocab.php on line 146

Notice: Undefined index: @id in /home/sharonml/public_html/6floors.org/workspace/omeka-s/modules/CustomVocab/src/DataType/CustomVocab.php on line 166

**Comment by sharonmleon** [comment]
This might be user error because I stupidly used the admin interface URLs instead of the published ones.

**Comment by jimsafley** [comment]
The most recent commit (f44073fa4b043ae0d917f389e5ee345460607a2b) should fix the "Undefined index" notices.

**Comment by sharonmleon** [comment]
Fixed.

**Comment by sharonmleon** [comment]
Affirming that preexisting literal terms continue to function as expected upon upgrade of module.

**Comment by jimsafley** [comment]
Commit eff7e95ead2b42982a206d0266e7d1ef7fc8abab requires a higher version constraint (3.1.0) due to style changes needed to fix select dropdown width. We can release this once 3.1.0 is released.
