### ISSUE TITLE
Should CustomVocab datatypes be more like ValueSuggest in dropdown?

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/CustomVocab#3]
Custom Vocab and ValueSuggest take different approaches to representing themselves in the datatypes dropdown. I like Value Suggest's approach a bit better, and think it makes sense to switch up CustomVocab to follow that pattern.

![customvocab](https://user-images.githubusercontent.com/153262/29670752-aeb81ef8-88b5-11e7-8795-b47715b2298e.png)

**Comment by jimsafley** [comment]
e8cf0b9 should have done this. Habe you pulled the latest commits?

**Comment by patrickmj** [comment]
my bad! yep, that has the fix
