### ISSUE TITLE
Feature request fancy search boxes

### ISSUE THREAD

**Issue by bradgillap** [omeka-s-modules/CustomVocab#36]
Hello,

Currently custom vocab offers a regular dropdown when using a list of text items. 

But for lists with many items, like more than 5. This kind of search box is much more preferable while entering data quickly.

![image](https://user-images.githubusercontent.com/1094081/231037484-b8875e12-5998-4507-b0c6-f91431152b18.png)

**Comment by jimsafley** [comment]
Thanks for the suggestion. It should be in the next release. No ETA yet.

**Comment by Daniel-KM** [comment]
This is strange, it was already implemented in #4 some years ago, it was lost later.

**Comment by bradgillap** [comment]
Yeah, I had one of our devs at work look into it and her theory is it likely is to do with a framework switch to Laminas. Like it's not available as part of that framework? Just to add to the goose chase.

**Comment by zerocrates** [comment]
It looks to have been (accidentally?) removed quite recently in b75c7a8409240c0e771efde6235b2bd1ab342bd3
