### ISSUE TITLE
Testing: Import / export custom vocabs

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/CustomVocab#37]
Addressing #34, the [import-export](https://github.com/omeka-s-modules/CustomVocab/compare/import-export) branch adds import/export features to the CustomVocab module. Not only can administrators import new vocabularies, they can also update existing ones.

To test this, check out the `import-export` branch. You should see an "Import" button on the custom vocab browse page. Use this is import new vocabularies. You should also see import and export icons in each row. You should only see these icons for "terms" and "URIs" vocabularies, as "Items" vocabularies cannot be imported or exported. Use these icons to import (i.e. update) existing vocabularies.

Export a few vocabs, making sure that no error occurs and the resulting file is a JSON file containing vocab data. Import a few new vocabs, using the export files you just created. Importing a new vocab should take you to the add form with the provided data already filled out. Importing into an existing vocabulary should take you to the edit form with the data replaced with the provided data.

Note that I've made quite a few changes across the codebase, so a general test of the module's existing fuctionality will be needed.

**Comment by allanaaa** [comment]
Everything works well. I don't like the similarity of the import and export icons at that size. And I think "Import" on an existing vocab should more properly be "Update" or something else, which gives us the option to use some other icon. Or no icons at all.

**Comment by jimsafley** [comment]
I don't imagine that users will be importing and exporting very often. I could move those actions to "Import" and "Export" buttons on the edit page. Is that sufficient?

**Comment by jimsafley** [comment]
I've moved the export and import controls to the edit page. @allanaaa Is this satisfactory?

**Comment by allanaaa** [comment]
That's an improvement. I would still rather the button say "Update" than "Import", and maybe "Save" instead of "Submit" while you're there?

**Comment by allanaaa** [comment]
I'm happy with this, and the documentation has been updated: https://github.com/omeka/omeka-s-enduser/pull/176
