### ISSUE TITLE
Only 25 vocabs shown in browse page

### ISSUE THREAD

**Issue by ArdenKirkland** [omeka-s-modules/CustomVocab#40]
I'm experimenting with many different customVocabs, but the browse page only shows the first 25, in alphabetical order. I probably have around 30 so far. I can't find where in the code this limit is set - can it be updated to show all customVocabs on the browse page, no matter how many?

**Comment by jimsafley** [comment]
Yes, that's a bug. Actually, more of an unintentional omission than a bug. I've pushed [the fix](7b40b208bdec88c0cb20e605c4c8ea97204a70ea) and made [a new release](https://github.com/omeka-s-modules/CustomVocab/releases/tag/v2.0.2). It should be published on [the modules page](https://omeka.org/s/modules/CustomVocab/) tomorrow. Thanks for reporting this!

**Comment by ArdenKirkland** [comment]
That was a very quick fix - thank you so much!
