### ISSUE TITLE
Lists of Omeka S Resources

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/CustomVocab#9]
You know what would be awesome (and decidedly less simple)? If we could make a list of already existing Omeka S resources as the options for a custom vocab menu.

**Comment by patrickmj** [comment]
That does kinda make sense, but would call for very site-specific human planning. It'd have to have planning and structure for what items make sense to go into the custom vocab, then the code to do that. Ouch.

**Comment by sharonmleon** [comment]
Well, most complex template work requires planning, but each of the items would just be an OS:ID to add to the list, so the form could ask for datatype (string or OS:ID) and then take the input accordingly.
